substitutions:
  name: "esp32-speaker2"
  friendly_name: ESP32_Speaker-2

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota: 
  - platform: esphome
# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
 output_power: 10

i2s_audio:
  - i2s_lrclk_pin: GPIO26
    i2s_bclk_pin: GPIO25

media_player:
  - platform: i2s_audio
    name: None
    dac_type: external
    i2s_dout_pin: GPIO27
    mode: stereo
