substitutions:
  name: "esp-tagreader"
  friendly_name: ESP-TagReader

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota: 
  - platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 15

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

rc522_spi:
  cs_pin: GPIO15
  reset_pin: GPIO16

binary_sensor:
  - platform: rc522
    uid: 6A-6A-8C-80
    name: "Blue keychain"
  - platform: rc522
    uid: E3-F3-98-FE
    name: "Wite card"
  - platform: rc522
    uid: 04-83-FB-7A-68-19-90
    name: "Command drone"
